---
api:
  insecure: false
  dashboard: true
  debug: true

log:
  level: INFO

accessLog:
  format: common

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-general
          scheme: https
          permanent: true
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  web-general:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
      middlewares:
        - hsts@file
    http3: {}
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"
  web-docker-registry:
    address: ":444"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  web-home:
    address: ":446"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"
  web-defi:
    address: ":447"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  npm:
    address: ":448"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  api-nuget:
    address: ":449"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  photos:
    address: ":450"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  aur:
    address: ":451"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  pacman:
    address: ":452"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  flathub:
    address: ":453"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  funfair-nuget:
    address: ":455"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  funfair-prerelease-nuget:
    address: ":456"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

  monitoring:
    address: ":457"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "fc00::/7"
        - "fe80::/10"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${CLOUDFLARE_EMAIL}"
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true

experimental:
  plugins:
    traefik-api-token-middleware:
      moduleName: "github.com/Aetherinox/traefik-api-token-middleware"
      version: "v0.1.4"
